name: Publish To CocoaPods

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby & Bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true # also runs 'bundle install'

      - name: Sanity Check
        run: |
          bundle exec pod trunk me
          bundle exec pod spec lint

      - name: Publish
        run: |
          bundle exec pod trunk push
